### ISSUE TITLE
Multi-select not working

### ISSUE THREAD

**Issue by szymsza** [PatrickJunod/image-select-for-statamic#2]
After installing the latest version, fields with `multiple: true` still allow selecting only one image.

The reason for this bug is an outdated build - although `resources/js/fieldtypes/ImageSelect.vue` contains the new version with `checkbox` input supporting multi-select, the build at `dist/js/image-select.js` seems not to be updated, as it contains the old `radio` input type and no mention of the `multiple` config option.

My workaround is to build the assets manually (`cd vendor/patrickjunod/image-select && npm i && npx mix`) before publishing them. This should not be needed, however, and the new assets should be built by default.

**Comment by PatrickJunod** [comment]
Hi @szymsza, thanks for your message. It's been fixed in the latest release. Best regards, Patrick
